### ISSUE TITLE
Webpack build with version 3.2.8 is failing

### ISSUE THREAD

**Issue by martijnboland** [aspnet/jquery-validation-unobtrusive#79]
When using the latest version from NPM (3.2.8) with webpack, the following error occurres:
```
ERROR in ./node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js
Module not found: Error: Can't resolve 'jquery.validate' in '[path]\node_modules\jquery-validation-unobtrusive\dist'
 @ ./node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js 11:8-75
 @ multi bootstrap jquery jquery-validation jquery-validation-unobtrusive popper.js
```
I think webpack tries to resolve jquery.validate as a dependency (via AMD define) but it fails because it's probably known within webpack as jquery-validation. A workaround is to add the following rule to the webpack config:
```
module: {
  rules: [
    {
      parser: {
        amd: false,
      }
    }, 
   ...other rules...
  ]
}

**Comment by moise** [comment]
same issue here.

**Comment by dbengtsson** [comment]
Same here, downgrading to 3.2.6 works again. For those unfamiliar with semver: remove the ^ from package.json before 3.2.6 or it will force an update to 3.2.8 since it's a patchversion.

**Comment by dbengtsson** [comment]
Can someone point me in the direction of why CommonJS uses dashes (-) and AMD uses dots (.) for module naming? I thought I'd fix this but quickly realized my knowledge of AMD is very limited.

**Comment by kyrylovych** [comment]
The problem is that `jquery unobtrusive` is trying to load module with name *jquery.validate*. 
But such module is not valid because in latest version of `jquery-validation` export was defined as *jquery* 
Check it here.
[https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.js](https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.js)
```javascript
(function( factory ) {
	if ( typeof define === "function" && define.amd ) {
		define( ["jquery"], factory );
	} else if (typeof module === "object" && module.exports) {
		module.exports = factory( require( "jquery" ) );
	} else {
		factory( jQuery );
	}
}(function( $ ) {
// jquery validation code 
})
```
I think this is bug in `jquery-validation` itself because docs says that you need to require dependency *jquery.validate* but not *jquery*.

So the quick fix would just replacing *jquery.validate* to *jquery* in `jquery-validation-unobtrusive` library or *jquery* to *jquery.validate* in `jquery-validation` library.

**Comment by kyrylovych** [comment]
Sorry guys, 

I haven't noticed the brackets in `define( ["jquery"], factory )`. 
This means that `jquery validation` is exported as anonymous module. 
But still, you can access it's name (in our case - *jquery-validation*)

The only way to resolve this issue is to change required dependency name in `jquery-validation-unobtrusive` library

```javascript
define("jquery.validate.unobtrusive", ['jquery.validate'], factory);
```
to 
```javascript
define("jquery.validate.unobtrusive", ['jquery-validation'], factory);
```

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this issue. One of our engineers will look into this.

**Comment by mkArtakMSFT** [comment]
@kichalla, can you please look into this and evaluate what options do we have? Thanks

**Comment by Eilon** [comment]
BTW if we fix this, this fix would go into the next milestone, which is 3.2.9 (because we already pushed 3.2.8).

**Comment by li0nsar3c00l** [comment]
Any ETA, when this will be solved?

**Comment by Eilon** [comment]
@li0nsar3c00l no ETA at this time, but hopefully not too far out.

**Comment by kichalla** [comment]
As suggested earlier in this thread, after doing the following change, Webpack build works fine:

`define("jquery.validate.unobtrusive", ['jquery.validate'], factory);`
to
`define("jquery.validate.unobtrusive", ['jquery-validation'], factory);`

**Comment by benface** [comment]
@kichalla This is not fixed. You changed it from `jquery.validate` to `jquery.validation`. It needs to be `jquery-validation`.

**Comment by Baune8D** [comment]
@kichalla Please re-open this issue. The problem persists.

**Comment by kichalla** [comment]
Ah, this was my bad. I did the verification using the correct name https://github.com/aspnet/jquery-validation-unobtrusive/issues/79#issuecomment-376511463, but my check-in was different. Re-opening this issue.

**Comment by li0nsar3c00l** [comment]
Since CI/CD is not implemented, when will this fix be pushed to npm?

**Comment by colindekker** [comment]
For people using webpack, the easiest option is to alias `jquery.validate` in the resolve block of webpack. Below tested with Webpack 4 (latest) and latest versions of both jquery-validation and jquery-validation-unobtrusive. 
This way there is no need to hack the `jquery-validation-unobtrusive` package files, and when the offending lines are fixed in a next release your webpack build will keep working.

```
alias: {
  "jquery.validation': "jquery-validation/dist/jquery.validate.js" 
},
```

**Comment by kichalla** [comment]
Just FYI, a new version (3.2.10) having the correct fix for this has been published to npm registry few minutes ago.

**Comment by davidliang2008** [comment]
Hmmm I am still seeing the problem. I got `jquery-validation: 1.18.0` and even `jquery-validation-unobtrusive:3.2.11` from npm and the issue still persists.
The only way I can get it working is to downgrade `jquery-validation-unobtrusive` back to 3.2.6.
